version: '3'
services:
  spark:
    build: .
    container_name: spark-job
    volumes:
      - .:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service_account_gcp.json
    command: >
      spark-submit
      --jars /opt/bitnami/spark/jars/gcs-connector-hadoop3-latest.jar
      /app/code/pyspark_local.py
